# -*- coding: utf-8 -*-
"""Single number 1,2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjL2n6snx2BSDHRWKtFo87WLRlkG-Aap
"""

# single number 1
def s1(a):
  n = 0
  for i in a:
    n ^= i
  return n
s1([1,1,2,2,3,3,4,5,4])

# single number 2
def s2(a):
  n = 0
  m = 0
  k =
  for i in a:
    n ^= i & ~m
    m ^= i & ~n

  return n

s2([1,1,1,3,4,4,4,5,5,5])